name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - uses: extractions/setup-just@v1

    - name: Run Tests
      run: just test
